# Test Output

In [20]:
import matplotlib as plt

In [21]:
import numpy as np

In [3]:
print("Hello world")

Hello world


This is a paragraph

In [2]:
from IPython.display import Image

In [3]:
Image(url='http://jupyter.org/assets/nav_logo.svg')

In [2]:
from pythreejs import *
from math import pi
import ipywidgets

In [4]:
cg = CylinderGeometry(
    radiusTop=5,
    radiusBottom=10,
    height=15,
    radialSegments=6,
    heightSegments=10,
    openEnded=False,
    thetaStart=0,
    thetaLength=2.0*pi)
display(cg)

Preview(child=CylinderGeometry(height=15.0, heightSegments=10, radiusBottom=10.0, radiusTop=5.0), shadowMap=We…

In [2]:

vertices = [
    [0, 0, 0],
    [0, 0, 1],
    [0, 1, 0],
    [0, 1, 1],
    [1, 0, 0],
    [1, 0, 1],
    [1, 1, 0],
    [1, 1, 1]
]

faces = [
    [0, 1, 3],
    [0, 3, 2],
    [0, 2, 4],
    [2, 6, 4],
    [0, 4, 1],
    [1, 4, 5],
    [2, 3, 6],
    [3, 7, 6],
    [1, 5, 3],
    [3, 5, 7],
    [4, 6, 5],
    [5, 6, 7]
]

vertexcolors = ['#000000', '#0000ff', '#00ff00', '#ff0000',
                '#00ffff', '#ff00ff', '#ffff00', '#ffffff']

# Map the vertex colors into the 'color' slot of the faces
faces = [f + [None, [vertexcolors[i] for i in f]] for f in faces]

# Create the geometry:
cubeGeometry = Geometry(vertices=vertices,
    faces=faces,
    colors=vertexcolors)
# Calculate normals per face, for nice crisp edges:
cubeGeometry.exec_three_obj_method('computeFaceNormals')

# Create a mesh. Note that the material need to be told to use the vertex colors.
myobjectCube = Mesh(
    geometry=cubeGeometry,
    material=MeshLambertMaterial(vertexColors='VertexColors'),
    position=[-0.5, -0.5, -0.5],   # Center the cube
)

# Set up a scene and render it:
cCube = PerspectiveCamera(position=[3, 3, 3], fov=20,
                      children=[DirectionalLight(color='#ffffff', position=[-3, 5, 1], intensity=0.5)])
sceneCube = Scene(children=[myobjectCube, cCube, AmbientLight(color='#dddddd')])

rendererCube = Renderer(camera=cCube, background='black', background_opacity=1,
                        scene=sceneCube, controls=[OrbitControls(controlling=cCube)])

display(rendererCube)

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(intensity=0.5, position=(-3.0, 5.0, 1.0), quatern…

In [7]:
from AmpScan import AmpObject

In [8]:
Amp = AmpObject("sample_stl_sphere_BIN.stl")

In [9]:
Amp.vert

array([[-1.       ,  0.       ,  0.       ],
       [-0.9904389, -0.1379523,  0.       ],
       [-0.9904389,  0.1379523,  0.       ],
       ...,
       [ 0.9904389, -0.1379523,  0.       ],
       [ 0.9904389,  0.1379523,  0.       ],
       [ 1.       ,  0.       ,  0.       ]], dtype=float32)

In [10]:
Amp.faces

array([[454, 453, 412],
       [406, 454, 412],
       [496, 453, 454],
       ...,
       [ 57,  77,  87],
       [101, 109,  77],
       [133,  87, 109]])

In [12]:
vertices = list(Amp.vert)

In [14]:
Amp.vert

array([[-1.       ,  0.       ,  0.       ],
       [-0.9904389, -0.1379523,  0.       ],
       [-0.9904389,  0.1379523,  0.       ],
       ...,
       [ 0.9904389, -0.1379523,  0.       ],
       [ 0.9904389,  0.1379523,  0.       ],
       [ 1.       ,  0.       ,  0.       ]], dtype=float32)

In [27]:
import numpy

In [29]:
vertices = Amp.vert

In [36]:
vertices=vertices.tolist()

In [31]:
faces = Amp.faces

In [34]:
faces = faces.tolist()

In [40]:
Geometry(vertices=vertices, faces=faces)

Preview(child=Geometry(colors=['#ffffff'], faces=([454, 453, 412], [406, 454, 412], [496, 453, 454], [405, 412…

In [41]:
Amp2 = AmpObject("M8_Cast1_Scan1.stl")

In [42]:
scanvert=Amp2.vert

In [43]:
scanvert=scanvert.tolist()

In [50]:
scanfaces=Amp2.faces

In [51]:
scanfaces=scanfaces.tolist()

In [55]:
vertexcolors = ['#000000', '#0000ff', '#00ff00', '#ff0000',
                '#00ffff', '#ff00ff', '#ffff00', '#ffffff']
Geometry(vertices=scanvert, faces=scanfaces, colors=vertexcolors)

Preview(child=Geometry(colors=['#000000', '#0000ff', '#00ff00', '#ff0000', '#00ffff', '#ff00ff', '#ffff00', '#…

In [56]:
scangeom  =Geometry(vertices=scanvert, faces=scanfaces, colors=vertexcolors)

In [86]:
myobject = Mesh(
    geometry=scangeom,
    material=MeshLambertMaterial(color='red')
)
scene.background="#ffffff"


In [87]:
myobject

Preview(child=Mesh(geometry=Geometry(colors=['#000000', '#0000ff', '#00ff00', '#ff0000', '#00ffff', '#ff00ff',…