# Test Output

In [20]:
import matplotlib as plt

In [21]:
import numpy as np

In [3]:
print("Hello world")

Hello world


This is a paragraph

In [2]:
from IPython.display import Image

In [3]:
Image(url='http://jupyter.org/assets/nav_logo.svg')

In [1]:
from pythreejs import *
from math import pi

In [2]:
CylinderGeometry(
    radiusTop=5,
    radiusBottom=10,
    height=15,
    radialSegments=6,
    heightSegments=10,
    openEnded=False,
    thetaStart=0,
    thetaLength=2.0*pi)

Preview(child=CylinderGeometry(height=15.0, heightSegments=10, radiusBottom=10.0, radiusTop=5.0), shadowMap=We…

In [4]:
dir(pythreejs)

['AmbientLight',
 'Bool',
 'BoxGeometry',
 'BufferAttribute',
 'BufferGeometry',
 'CFloat',
 'CInt',
 'Color',
 'DataTexture',
 'DirectionalLight',
 'EXTENSION_SPEC_VERSION',
 'Geometry',
 'Group',
 'Instance',
 'Line',
 'List',
 'Material',
 'Mesh',
 'MeshLambertMaterial',
 'PlotMesh',
 'SphereGeometry',
 'Sprite',
 'SpriteMaterial',
 'SurfaceGeometry',
 'SurfaceGrid',
 'TextTexture',
 'Texture',
 'Unicode',
 'Widget',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__warningregistry__',
 'absolute_import',
 'grid_indices_gen',
 'height_texture',
 'lights_color',
 'lights_gray',
 'make_text',
 'np',
 'npm_pkg_name',
 'observe',
 'validate',
 'widget_serialization']

In [5]:

vertices = [
    [0, 0, 0],
    [0, 0, 1],
    [0, 1, 0],
    [0, 1, 1],
    [1, 0, 0],
    [1, 0, 1],
    [1, 1, 0],
    [1, 1, 1]
]

faces = [
    [0, 1, 3],
    [0, 3, 2],
    [0, 2, 4],
    [2, 6, 4],
    [0, 4, 1],
    [1, 4, 5],
    [2, 3, 6],
    [3, 7, 6],
    [1, 5, 3],
    [3, 5, 7],
    [4, 6, 5],
    [5, 6, 7]
]

vertexcolors = ['#000000', '#0000ff', '#00ff00', '#ff0000',
                '#00ffff', '#ff00ff', '#ffff00', '#ffffff']

# Map the vertex colors into the 'color' slot of the faces
faces = [f + [None, [vertexcolors[i] for i in f]] for f in faces]

# Create the geometry:
cubeGeometry = Geometry(vertices=vertices,
    faces=faces,
    colors=vertexcolors)
# Calculate normals per face, for nice crisp edges:
cubeGeometry.exec_three_obj_method('computeFaceNormals')

# Create a mesh. Note that the material need to be told to use the vertex colors.
myobjectCube = Mesh(
    geometry=cubeGeometry,
    material=MeshLambertMaterial(vertexColors='VertexColors'),
    position=[-0.5, -0.5, -0.5],   # Center the cube
)

# Set up a scene and render it:
cCube = PerspectiveCamera(position=[3, 3, 3], fov=20,
                      children=[DirectionalLight(color='#ffffff', position=[-3, 5, 1], intensity=0.5)])
sceneCube = Scene(children=[myobjectCube, cCube, AmbientLight(color='#dddddd')])

rendererCube = Renderer(camera=cCube, background='black', background_opacity=1,
                        scene=sceneCube, controls=[OrbitControls(controlling=cCube)])

display(rendererCube)

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(intensity=0.5, position=(-3.0, 5.0, 1.0), quatern…

In [6]:
help(Geometry)

Help on class Geometry in module pythreejs.core.Geometry:

class Geometry(pythreejs.core.Geometry_autogen.Geometry)
 |  Geometry
 |  
 |  Autogenerated by generate-wrappers.js
 |  See https://threejs.org/docs/#api/core/Geometry
 |  
 |  Method resolution order:
 |      Geometry
 |      pythreejs.core.Geometry_autogen.Geometry
 |      pythreejs.core.BaseGeometry_autogen.BaseGeometry
 |      pythreejs._base.Three.ThreeWidget
 |      ipywidgets.widgets.widget.Widget
 |      ipywidgets.widgets.widget.LoggingHasTraits
 |      traitlets.traitlets.HasTraits
 |      traitlets.traitlets.HasDescriptors
 |      builtins.object
 |  
 |  Class methods defined here:
 |  
 |  from_geometry(geometry, store_ref=False) from traitlets.traitlets.MetaHasTraits
 |      Creates a PlainGeometry of another geometry.
 |      
 |      store_ref determines if the reference is stored after initalization.
 |      If it is, it will be used for future embedding.
 |      
 |      NOTE:
 |      The PlainGeometry will c

In [7]:
from AmpScan import AmpObject

In [8]:
Amp = AmpObject("sample_stl_sphere_BIN.stl")

In [9]:
Amp.vert

array([[-1.       ,  0.       ,  0.       ],
       [-0.9904389, -0.1379523,  0.       ],
       [-0.9904389,  0.1379523,  0.       ],
       ...,
       [ 0.9904389, -0.1379523,  0.       ],
       [ 0.9904389,  0.1379523,  0.       ],
       [ 1.       ,  0.       ,  0.       ]], dtype=float32)

In [10]:
Amp.faces

array([[454, 453, 412],
       [406, 454, 412],
       [496, 453, 454],
       ...,
       [ 57,  77,  87],
       [101, 109,  77],
       [133,  87, 109]])

In [11]:
Geometry(vertices=Amp.vert, faces=Amp.faces)

TraitError: The 'vertices' trait of a Geometry instance must be a list, but a value of class 'numpy.ndarray' (i.e. array([[-1.       ,  0.       ,  0.       ],
       [-0.9904389, -0.1379523,  0.       ],
       [-0.9904389,  0.1379523,  0.       ],
       ...,
       [ 0.9904389, -0.1379523,  0.       ],
       [ 0.9904389,  0.1379523,  0.       ],
       [ 1.       ,  0.       ,  0.       ]], dtype=float32)) was specified.

In [12]:
vertices = list(Amp.vert)

In [13]:
vertices

[array([-1.,  0.,  0.], dtype=float32),
 array([-0.9904389, -0.1379523,  0.       ], dtype=float32),
 array([-0.9904389,  0.1379523,  0.       ], dtype=float32),
 array([-0.9876884 , -0.08224247, -0.1330711 ], dtype=float32),
 array([-0.9876884 , -0.08224247,  0.1330711 ], dtype=float32),
 array([-0.9876884 ,  0.08224247, -0.1330711 ], dtype=float32),
 array([-0.9876884 ,  0.08224247,  0.1330711 ], dtype=float32),
 array([-0.9663926, -0.220117 , -0.1327925], dtype=float32),
 array([-0.9663926, -0.220117 ,  0.1327925], dtype=float32),
 array([-0.9663926,  0.220117 , -0.1327925], dtype=float32),
 array([-0.9663926,  0.220117 ,  0.1327925], dtype=float32),
 array([-0.9638612,  0.       , -0.2664047], dtype=float32),
 array([-0.9638612,  0.       ,  0.2664047], dtype=float32),
 array([-0.9619384, -0.2732666,  0.       ], dtype=float32),
 array([-0.9619384,  0.2732666,  0.       ], dtype=float32),
 array([-0.9510565, -0.1624599, -0.2628656], dtype=float32),
 array([-0.9510565, -0.1624599,  

In [14]:
Amp.vert

array([[-1.       ,  0.       ,  0.       ],
       [-0.9904389, -0.1379523,  0.       ],
       [-0.9904389,  0.1379523,  0.       ],
       ...,
       [ 0.9904389, -0.1379523,  0.       ],
       [ 0.9904389,  0.1379523,  0.       ],
       [ 1.       ,  0.       ,  0.       ]], dtype=float32)

In [27]:
import numpy

In [28]:
help(numpy.ndarray)

Help on class ndarray in module numpy:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |

In [29]:
vertices = Amp.vert

In [36]:
vertices=vertices.tolist()

In [31]:
faces = Amp.faces

In [34]:
faces = faces.tolist()

In [35]:
faces

[[454, 453, 412],
 [406, 454, 412],
 [496, 453, 454],
 [405, 412, 453],
 [368, 412, 367],
 [336, 368, 367],
 [406, 412, 368],
 [405, 367, 412],
 [492, 454, 450],
 [480, 492, 450],
 [496, 454, 492],
 [406, 450, 454],
 [449, 453, 491],
 [479, 449, 491],
 [405, 453, 449],
 [496, 491, 453],
 [363, 409, 359],
 [332, 363, 359],
 [405, 409, 363],
 [401, 359, 409],
 [330, 359, 355],
 [328, 330, 355],
 [332, 359, 330],
 [401, 355, 359],
 [367, 363, 334],
 [336, 367, 334],
 [405, 363, 367],
 [332, 334, 363],
 [445, 409, 449],
 [479, 445, 449],
 [401, 409, 445],
 [405, 449, 409],
 [410, 364, 360],
 [402, 410, 360],
 [406, 364, 410],
 [333, 360, 364],
 [356, 360, 331],
 [329, 356, 331],
 [402, 360, 356],
 [333, 331, 360],
 [450, 410, 446],
 [480, 450, 446],
 [406, 410, 450],
 [402, 446, 410],
 [335, 364, 368],
 [336, 335, 368],
 [333, 364, 335],
 [406, 368, 364],
 [523, 524, 556],
 [543, 523, 556],
 [496, 524, 523],
 [544, 556, 524],
 [575, 556, 576],
 [596, 575, 576],
 [543, 556, 575],
 [544, 576

In [40]:
Geometry(vertices=vertices, faces=faces)

Preview(child=Geometry(colors=['#ffffff'], faces=([454, 453, 412], [406, 454, 412], [496, 453, 454], [405, 412…

In [39]:
vertices

[[-1.0, 0.0, 0.0],
 [-0.9904388785362244, -0.1379522979259491, 0.0],
 [-0.9904388785362244, 0.1379522979259491, 0.0],
 [-0.987688422203064, -0.0822424665093422, -0.13307109475135803],
 [-0.987688422203064, -0.0822424665093422, 0.13307109475135803],
 [-0.987688422203064, 0.0822424665093422, -0.13307109475135803],
 [-0.987688422203064, 0.0822424665093422, 0.13307109475135803],
 [-0.9663925766944885, -0.2201170027256012, -0.13279250264167786],
 [-0.9663925766944885, -0.2201170027256012, 0.13279250264167786],
 [-0.9663925766944885, 0.2201170027256012, -0.13279250264167786],
 [-0.9663925766944885, 0.2201170027256012, 0.13279250264167786],
 [-0.9638612270355225, 0.0, -0.2664046883583069],
 [-0.9638612270355225, 0.0, 0.2664046883583069],
 [-0.9619383811950684, -0.27326661348342896, 0.0],
 [-0.9619383811950684, 0.27326661348342896, 0.0],
 [-0.9510564804077148, -0.16245989501476288, -0.2628656029701233],
 [-0.9510564804077148, -0.16245989501476288, 0.2628656029701233],
 [-0.9510564804077148, 0.

In [41]:
Amp2 = AmpObject("M8_Cast1_Scan1.stl")

In [42]:
scanvert=Amp2.vert

In [43]:
scanvert=scanvert.tolist()

In [44]:
scanvert

[[-54.4482536315918, 5.75036096572876, -69.07861328125],
 [-54.44446563720703, 2.7506065368652344, -69.01692199707031],
 [-54.43195343017578, 5.814332485198975, -66.07624053955078],
 [-54.29474639892578, 2.8170125484466553, -66.0092544555664],
 [-54.2918586730957, 2.6897177696228027, -72.0125961303711],
 [-54.27552795410156, 5.880860805511475, -63.06830978393555],
 [-54.22058868408203, 5.690842628479004, -72.0713119506836],
 [-54.10734176635742, 2.884106397628784, -63.000099182128906],
 [-54.09079360961914, 8.820382118225098, -66.12425231933594],
 [-54.06641387939453, 5.94835090637207, -60.05828857421875],
 [-54.01490020751953, 8.75809383392334, -69.12296295166016],
 [-53.9650993347168, 8.88634967803955, -63.11753845214844],
 [-53.95328903198242, -0.24025362730026245, -68.93589782714844],
 [-53.913002014160156, -0.30319222807884216, -71.93602752685547],
 [-53.88567352294922, 2.9518256187438965, -59.98957824707031],
 [-53.79991912841797, 2.635021448135376, -74.99481201171875],
 [-53.741

In [50]:
scanfaces=Amp2.faces

In [51]:
scanfaces=scanfaces.tolist()

In [55]:
vertexcolors = ['#000000', '#0000ff', '#00ff00', '#ff0000',
                '#00ffff', '#ff00ff', '#ffff00', '#ffffff']
Geometry(vertices=scanvert, faces=scanfaces, colors=vertexcolors)

Preview(child=Geometry(colors=['#000000', '#0000ff', '#00ff00', '#ff0000', '#00ffff', '#ff00ff', '#ffff00', '#…

In [56]:
scangeom  =Geometry(vertices=scanvert, faces=scanfaces, colors=vertexcolors)

In [86]:
myobject = Mesh(
    geometry=scangeom,
    material=MeshLambertMaterial(color='red')
)
scene.background="#ffffff"


In [87]:
myobject

Preview(child=Mesh(geometry=Geometry(colors=['#000000', '#0000ff', '#00ff00', '#ff0000', '#00ffff', '#ff00ff',…